#!/usr/bin/env bash

# 
# Description:
# 
#   Modifies default browser via `xdg-settings`
# 
# Depends:
# 
#   xdg-settings
# 
# Usage:
# 
#   ./btog {input}
# 
# Available {input}s:
# 
#   ff, ffd, chrome
# 

input=${1:-}
ff="firefox.desktop"
ffd="firefox-developer.desktop"
chrome="google-chrome.desktop"

# commands

set_cmd="xdg-settings set default-web-browser"
confirm_cmd="xdg-settings check default-web-browser"

# functions

set() {
    x="${1}"
    cmd=$(${set_cmd} "${x}")

    echo
    echo "Setting default browser to ${x}.."

    if [[ ${cmd} ]]; then
        echo
        echo "Default browser set to ${x}."
    fi
}

confirm() {
    x="${1}"
    cmd=$(${confirm_cmd} "${x}")

    if [[ ${cmd} = "yes" ]]; then
        echo
        echo "Done!"
    else
        echo
        echo "Property setting has failed."
        echo
        echo "Exiting!"; exit 0
    fi
}

# OG Firefox
if [[ ${input} = "ff" ]]; then
    set ${ff}
    confirm ${ff}

# Firefox Developer Edition
elif [[ ${input} = "ffd" ]]; then
    set ${ffd}
    confirm ${ffd}

# Google Chrome
elif [[ ${input} = "chrome" ]]; then
    set ${chrome}
    confirm ${chrome}
else
    echo
    echo "No valid input!"
    echo
    echo "Exiting.."; exit 0
fi
